### ISSUE TITLE
Add Derek Featherstone's course "UX Foundations: Accessibility"

### ISSUE THREAD

**Issue by carmacleod** [mgifford/a11y-courses#13]
I guess this would go under "Private (paid)" but note that lynda.com has a 30-day free trial feature.
https://www.lynda.com/Accessibility-tutorials/Foundations-UX-Accessibility/435008-2.html

**Comment by scottaohara** [comment]
Hi @carmacleod would you like to make a PR to add this to the repo?  If not, I can add it.  Thanks for the suggestion!

**Comment by scottaohara** [comment]
[resolved via this commit](https://github.com/mgifford/a11y-courses/commit/7d1a48bd1b9115aab2fa512b92d4b1a17a2f744e)

**Comment by carmacleod** [comment]
Oops - sorry. Have been on vacation for a month - just got back today. Thanks for adding this!
