### ISSUE TITLE
Top people to follow

### ISSUE THREAD

**Issue by joe-watkins** [mgifford/a11y-courses#20]
Howdy! Great resource :) I've added a link to your resources and would love to add a link to my little project which is a list of folks in the accessibility community to follow on social media.

https://github.com/joe-watkins/top-people-to-follow-in-web-accessibility

What ya think?

**Comment by scottaohara** [comment]
Hey @joe-watkins, I added your repo to the [reading materials file](https://github.com/mgifford/a11y-courses/blob/master/Reading-Material.md) for now. 

May need to think about this a bit more and map out some better/additional sectioning, but more than glad to have your repo on the list :)

**Comment by weboverhauls** [comment]
@scottaohara Good idea, thanks.

@joe-watkins Some ideas for your People list:
`@ianhamilton_ @iandevlin @IanPouncey @ianmcburnie @vick08`
